apiVersion: v1
kind: Namespace
metadata:
  name: products-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: products-system

spec:
  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products

    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: products-api
        image: service-image

        ports:
        - name: products-api
          containerPort: 3000
        - name: products-api-debug
          containerPort: 4000

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu


apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system
