apiVersion: v1
kind: Namespace
metadata:
  name: products-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: products-system

spec:
  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products

    spec:
      terminationGracePeriodSeconds: 60

containers:
      - name: products-api
        image: service-image
