apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: products-system

spec:
  selector:
    matchLabels:
      app: products

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: products

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      
      containers:
        - name: products-api
          resources:
            requests:
              cpu: "500m" 
            limits:
              cpu: "500m"