apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: products-system

spec:
  type: ClusterIP

  ports:
  - name: products-api
    port: 3000
    targetPort: products-api
  - name: products-api-debug
    port: 4000
    targetPort: products-api-debug
