apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/products/
patches:
- path: ./dev-products-patch-deploy.yaml
images:
- name: service-image
  newName: localhost/kristi/products
  newTag: 0.0.1
